### PR TITLE
an MQTT daemon

### PR DESCRIPTION
**Pull request by cspiel1**
A mqtt client that sends periodically leaf information to a configured MQTT
broker.

### CODE REVIEW

**Comment by cspiel1** [comment]
@filcole: Tested in home assistant. If you like it you may merge this. ;-)

**Comment by filcole** [comment]
This looks like it's polling the Nissan servers every 30 seconds, which I think is likely to be 
1) Quite noisy for Nissan servers
2) Has potential to run the 12V battery flat, because the 12V battery doesn't charge whilst the car is plugged in

**Comment by cspiel1** [comment]
No it should be only once an hour.
Then, when a `request_upodate()` was sent it polls the server every 15 seconds until the status  could be retrieved.

Sorry, the variable `sleepsecs` is unused. I drop it.

Following PRs would allow a separate timing during charging, like the hass plugin has.

Edit: Ah, the first check if status was updated is done after 30 seconds.

**Comment by cspiel1** [comment]
Had it running 24 hours and it seems to work. It requests an update once an hour. Maybe the delay should be adjusted for the first status get. There are these error messages in the log:
```
Oct 01 04:05:27 fspctl leafd.py[1869]: requesting ...
Oct 01 04:05:28 fspctl leafd.py[1869]: INFO:pycarwings2.pycarwings2:carwings error; logging in and trying request again: {'status': 408}
Oct 01 05:05:27 fspctl leafd.py[1869]: requesting ...
Oct 01 05:05:28 fspctl leafd.py[1869]: INFO:pycarwings2.pycarwings2:carwings error; logging in and trying request again: {'status': 408}
```
I'll try with 45 seconds.

**Comment by cspiel1** [comment]
The error message:
```
INFO:pycarwings2.pycarwings2:carwings error; logging in and trying request again: {'status': 408}
```
seems to be normal. A longer delay does not change anything. Also
```
408 Request Timeout
The server timed out waiting for the request
```
doesn't look like a longer delay might help here.

Anyway, the daemon works and the values are updated once an hour. From my side this is ready for the merge, if you like it. Let me know if I could improve something!

**Comment by cspiel1** [comment]
The last commit solves the 408 status code warning.

**Comment by cspiel1** [comment]
Okay, I guess that  you are not interested in the MQTT daemon. Maybe it doesn't fit very well into the examples folder. So I should create an application module that depends on pycarwings2. Thanks for this python library!

For now leafd.py can be found in my clone.

**Pull request closed without merging**
